USE sakila;
-- List the number of films per category.

SELECT category.name, COUNT(film_category.film_id) AS Number_of_films
FROM film_category
INNER JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name;

-- Retrieve the store ID, city, and country for each store.




SELECT
	city.city,
    country.country,
    COUNT(store.store_id) AS TOTAL_STORES
FROM
    store
INNER JOIN
    city_id ON store.city_id = city.city_id
INNER JOIN
    country_id ON city.country_id = country.country_id
GROUP BY
	city.city, country.country;
    -----
    -- Calculate the total revenue generated by each store in dollars.
    
SELECT 
	store.store_id ,
	SUM(payment.amount) AS total_revenue
FROM
	store
INNER JOIN
	staff on store.store_id = staff.store_id
INNER JOIN
	payment on staff.staff_id = payment.staff_id
GROUP BY 
	store.store_id;
    
--- Determine the average running time of films for each category
SELECT
	category_name,
	AVG(film.length) AS average_RT
FROM 
	film_category
JOIN
	film_category.film_id = film.film_id

GROUP BY 
	category_name;

    
    

